-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.order_items
(
    item_id serial NOT NULL,
    vendor_order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    price_at_purchase numeric(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.parent_orders
(
    parent_order_id serial NOT NULL,
    user_id integer NOT NULL,
    total_amount numeric(12, 2) NOT NULL,
    payment_status character varying(50) COLLATE pg_catalog."default" DEFAULT 'paid'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT parent_orders_pkey PRIMARY KEY (parent_order_id)
);

CREATE TABLE IF NOT EXISTS public.payouts
(
    payout_id serial NOT NULL,
    vendor_id integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'requested'::character varying,
    processed_at timestamp with time zone,
    CONSTRAINT payouts_pkey PRIMARY KEY (payout_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    vendor_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    stock_quantity integer NOT NULL DEFAULT 0,
    details jsonb,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vendor_orders
(
    vendor_order_id serial NOT NULL,
    parent_order_id integer NOT NULL,
    vendor_id integer NOT NULL,
    order_total numeric(12, 2) NOT NULL,
    commission_amount numeric(12, 2) NOT NULL,
    vendor_payout_amount numeric(12, 2) NOT NULL,
    shipping_status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    CONSTRAINT vendor_orders_pkey PRIMARY KEY (vendor_order_id)
);

CREATE TABLE IF NOT EXISTS public.vendors
(
    vendor_id serial NOT NULL,
    user_id integer,
    store_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    commission_rate numeric(5, 2) DEFAULT 5.00,
    balance numeric(12, 2) DEFAULT 0.00,
    CONSTRAINT vendors_pkey PRIMARY KEY (vendor_id),
    CONSTRAINT vendors_store_name_key UNIQUE (store_name),
    CONSTRAINT vendors_user_id_key UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_vendor_order_id_fkey FOREIGN KEY (vendor_order_id)
    REFERENCES public.vendor_orders (vendor_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.parent_orders
    ADD CONSTRAINT parent_orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payouts
    ADD CONSTRAINT payouts_vendor_id_fkey FOREIGN KEY (vendor_id)
    REFERENCES public.vendors (vendor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_vendor_id_fkey FOREIGN KEY (vendor_id)
    REFERENCES public.vendors (vendor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendor_orders
    ADD CONSTRAINT vendor_orders_parent_order_id_fkey FOREIGN KEY (parent_order_id)
    REFERENCES public.parent_orders (parent_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendor_orders
    ADD CONSTRAINT vendor_orders_vendor_id_fkey FOREIGN KEY (vendor_id)
    REFERENCES public.vendors (vendor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendors
    ADD CONSTRAINT vendors_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS vendors_user_id_key
    ON public.vendors(user_id);

END;